name: voice_message_package
description: Flutter package to play voice message in chats.
version: 0.0.75
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.21
  syncfusion_flutter_sliders: ^20.1.55
  audio_video_progress_bar: ^0.10.0
  flutter_cache_manager: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2


